### ISSUE TITLE
docker: Invalid hostPort on OSX 11.4

### ISSUE THREAD

**Issue by dancaron** [sorrell/docker-agensgraph-extension#1]
OSX 11.4 Big Sur

input:
docker run -it -e POSTGRES_PASSWORD=mypassword -pHostPort:5432 sorrell/agensgraph-extension

output:
docker: Invalid hostPort: HostPort.
See 'docker run --help'.

fix:
docker run -it -e POSTGRES_PASSWORD=mypassword -p 5432 sorrell/agensgraph-extension

**Comment by joefagan** [comment]
On windows the docker run needs to look like the following to get to the server on port 5432
```
docker run -it -e POSTGRES_PASSWORD=mypassword -p 5432:5432 sorrell/agensgraph-extension
```

**Comment by vinzenz** [comment]
@sorrell  You can close this issue, this you did already merge the fix for this.
